# Generated by Django 4.0.5 on 2022-07-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_origen', models.CharField(max_length=200)),
                ('ubicacion_destino', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='lcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mercado.categoria'),
        ),
    ]
