# Generated by Django 4.0.5 on 2022-07-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_rename_lcategory_producto_lcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ubication',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
