# Generated by Django 4.0.5 on 2022-07-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_empresa_ubication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='ubication',
            new_name='ubicacion',
        ),
    ]
