# Generated by Django 4.0.5 on 2022-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_rename_ubication_empresa_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to=''),
        ),
    ]
