# Generated by Django 4.0.5 on 2022-07-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_alter_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lempresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercado.empresa'),
        ),
    ]
