# Generated by Django 4.0.5 on 2022-07-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_producto_lempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='lempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.empresa'),
        ),
    ]
