# Generated by Django 4.0.5 on 2022-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_alter_producto_lempresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='ubicacion',
            new_name='latitud',
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitud',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
